const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const prices = {EURUSD:{price:1.0916,change:0.22,spread:0.0002,flag:'🇪🇺',name:'Euro / US Dollar'},XAUUSD:{price:2648.35,change:0.48,spread:0.50,flag:'🟡',name:'Gold (Spot)'},US100:{price:20843.7,change:0.37,spread:6.5,flag:'🇺🇸',name:'NASDAQ 100'}};
let profile='scalping', tab='open', botOn=false;
function fmt(sym,n){return sym==='EURUSD'?n.toFixed(4):sym==='XAUUSD'?n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):n.toLocaleString('en-US',{minimumFractionDigits:1,maximumFractionDigits:1});}
function renderMarket(){ $('#ticker').innerHTML=Object.entries(prices).map(([s,p])=>`<div class="ticker-item"><b>${s}</b>${fmt(s,p.price)} <span>+${p.change.toFixed(2)}%</span></div>`).join(''); $('#marketRows').innerHTML=Object.entries(prices).map(([s,p])=>`<div class="market-row"><div><b><span class="flag">${p.flag}</span>${s}</b><small>${p.name}</small></div><div class="quote">${fmt(s,p.price)}<small>Bid</small></div><div class="quote">${fmt(s,p.price+p.spread)}<small>Ask · +${p.change.toFixed(2)}%</small></div></div>`).join('');}
const trades={open:[['1','🇪🇺 EURUSD','BUY','0.01','1.0898','1.0916','+$1.80','2026-10-08 16:42'],['2','🟡 XAUUSD','SELL','0.01','2,652.40','2,648.35','+$4.05','2026-10-08 16:27']],closed:[['3','🇺🇸 US100','BUY','0.01','20,780.2','20,843.7','+$6.35','2026-10-08 14:20'],['4','🇪🇺 EURUSD','SELL','0.01','1.0924','1.0912','+$1.20','2026-10-08 11:05'],['5','🟡 XAUUSD','BUY','0.01','2,640.00','2,637.50','−$2.50','2026-10-07 15:10']]};
function renderTrades(){ $('#tradeRows').innerHTML=trades[tab].map(r=>`<tr>${r.map((v,i)=>`<td class="${i===2?(v==='BUY'?'buy':'sell'):i===6?(v.startsWith('+')?'buy':'sell'):''}">${v}</td>`).join('')}</tr>`).join('');}
function drawChart(){const c=$('#equityChart'),ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=200;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const css=getComputedStyle(document.body),line=css.getPropertyValue('--line'),muted=css.getPropertyValue('--muted'),accent=css.getPropertyValue('--accent'),green=css.getPropertyValue('--green');ctx.strokeStyle=line;ctx.lineWidth=1;ctx.fillStyle=muted;ctx.font='10px sans-serif';for(let i=0;i<5;i++){let y=12+i*(h-30)/4;ctx.beginPath();ctx.moveTo(26,y);ctx.lineTo(w-5,y);ctx.stroke();ctx.fillText('$'+(10600-i*200).toLocaleString(),0,y-3)}const vals=[];let v=45;for(let i=0;i<60;i++){v+=(Math.random()-.42)*8;vals.push(Math.max(12,Math.min(h-40,v)));}ctx.beginPath();vals.forEach((y,i)=>{const x=27+i*(w-35)/(vals.length-1);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=green;ctx.lineWidth=2;ctx.stroke();ctx.lineTo(w-8,h-18);ctx.lineTo(27,h-18);ctx.closePath();ctx.globalAlpha=.12;ctx.fillStyle=accent;ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=muted;['00:00','04:00','08:00','12:00','16:00','20:00'].forEach((t,i)=>ctx.fillText(t,25+i*(w-45)/5,h-3));}
function setTheme(t){document.body.dataset.theme=t;$('#themeSelect').value=t;$$('.theme-tile').forEach(b=>b.classList.toggle('selected',b.dataset.theme===t));try{localStorage.setItem('castrofx-theme',t)}catch{}drawChart();}
try{const savedTheme=localStorage.getItem('castrofx-theme');if(['steel','cyber','emerald','light'].includes(savedTheme))setTheme(savedTheme)}catch{}
$('#themeSelect').addEventListener('change',e=>setTheme(e.target.value));$$('.theme-tile').forEach(b=>b.addEventListener('click',()=>setTheme(b.dataset.theme)));$('#accentColor').addEventListener('input',e=>{document.documentElement.style.setProperty('--accent',e.target.value);drawChart()});
$$('.profile').forEach(b=>b.addEventListener('click',()=>{profile=b.dataset.profile;$$('.profile').forEach(x=>x.classList.toggle('active',x===b));}));
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));renderTrades()}));
$$('.nav').forEach(b=>b.addEventListener('click',()=>{const target=b.dataset.target;$$('.nav').forEach(x=>x.classList.toggle('active',x===b));const el=$('#'+target);if(el)el.scrollIntoView({behavior:'smooth',block:'start'});}));
$('#botToggle').addEventListener('change',e=>{botOn=e.target.checked;$('#botState').textContent=botOn?'ON · DEMO ONLY':'OFF';$('#botState').className=botOn?'positive':'danger-text';$('#apiMessage').textContent=botOn?'Demo automation enabled in the interface only. No trades are being sent to MT5.':'Demo automation switched off. No orders are sent.';});
function config(){return {enabled:botOn,symbol:$('#symbol').value,lotSize:Number($('#lotSize').value),profile,stopLossPips:Number($('#sl').value),takeProfitPips:Number($('#tp').value),maxOpenTrades:Number($('#maxTrades').value),mode:'demo'}}
$('#saveSettings').addEventListener('click',()=>{const c=config();if(!Number.isFinite(c.lotSize)||c.lotSize<.01||c.lotSize>.1||!Number.isInteger(c.maxOpenTrades)||c.maxOpenTrades<1||c.maxOpenTrades>3||c.stopLossPips<5||c.takeProfitPips<5){$('#apiMessage').textContent='Check your values: lot size 0.01–0.10, max trades 1–3, SL/TP at least 5.';return;}$('#apiMessage').textContent='Demo settings validated locally. Press “Validate demo config” to check the server endpoint.';});
$('#testWebhook').addEventListener('click',async()=>{const out=$('#apiMessage');out.textContent='Validating configuration…';try{const r=await fetch('/api/mt5/webhook',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(prompt('Enter the server WEBHOOK_TOKEN. Do not enter your broker password.')||'')},body:JSON.stringify(config())});const data=await r.json();out.textContent=data.message||data.error||'Request finished.';}catch(e){out.textContent='Could not reach API. Start the Node server and configure .env first.';}});
$('#healthCheck').addEventListener('click',async()=>{const out=$('#healthResult');try{const r=await fetch('/api/health');const d=await r.json();out.textContent=`API ${d.ok?'online':'offline'} · mode: ${d.mode} · MT5 bridge: ${d.bridgeConnected?'connected':'not connected'}`;}catch(e){out.textContent='API unavailable. Start the server with npm start.';}});
renderMarket();renderTrades();drawChart();window.addEventListener('resize',drawChart);setInterval(()=>{for(const p of Object.values(prices)){p.price+=(Math.random()-.48)*(p.price>100?2:.0003);p.change+=(Math.random()-.5)*.015;}renderMarket();},2200);
